export const ErrorCode = {
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_ANONYMOUS_FAILED: "AUTH_ANONYMOUS_FAILED",
  AUTH_TURNSTILE_FAILED: "AUTH_TURNSTILE_FAILED",

  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  GROUP_INVITE_INVALID: "GROUP_INVITE_INVALID",
  GROUP_MEMBER_LIMIT: "GROUP_MEMBER_LIMIT",
  GROUP_ALREADY_MEMBER: "GROUP_ALREADY_MEMBER",

  EXPENSE_SAVE_FAILED: "EXPENSE_SAVE_FAILED",
  EXPENSE_SPLIT_MISMATCH: "EXPENSE_SPLIT_MISMATCH",
  EXPENSE_INVALID_REPEAT_END_DATE: "EXPENSE_INVALID_REPEAT_END_DATE",
  EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",

  UPLOAD_TYPE_INVALID: "UPLOAD_TYPE_INVALID",
  UPLOAD_SIZE_EXCEEDED: "UPLOAD_SIZE_EXCEEDED",
  UPLOAD_FAILED: "UPLOAD_FAILED",

  SETTLEMENT_CALC_FAILED: "SETTLEMENT_CALC_FAILED",

  NETWORK_OFFLINE: "NETWORK_OFFLINE",
  NETWORK_TIMEOUT: "NETWORK_TIMEOUT",
} as const;

export type ErrorCodeKey = keyof typeof ErrorCode;

export class ZplitError extends Error {
  code: ErrorCodeKey;
  override cause?: unknown;

  constructor(code: ErrorCodeKey, message: string, cause?: unknown) {
    super(message);
    this.name = "ZplitError";
    this.code = code;
    this.cause = cause;
  }
}
